### ISSUE TITLE
[FEATURE] Envoi du menu du jour par mail

### ISSUE THREAD

**Issue by LouiseRobert** [DehnCrest/CantocheBot#11]
Bonjour,

Il serait intéressant de recevoir le menu du jour sur notre boite mail de l'école, tous les jours à heure précise. 
9h par exemple.

**Comment by alexandredpy** [comment]
Hello,

As discussed with the developer, we won't work on this feature because we want to keep the bot easy to use.

Thanks a lot for your idea and your interest in this project.

Regards,
Alexandre
_Project Manager_
