### ISSUE TITLE
[FEATURE] Fix jour lors de demande spécifique

### ISSUE THREAD

**Issue by excoffit** [DehnCrest/CantocheBot#13]
**Describe the solution you'd like**
Display the day, when we ask for a specific day 

**Additional context**
In this case display 'Lundi':
![image](https://user-images.githubusercontent.com/55687388/136572900-2fb05d14-8884-4d5a-b071-1ff5623dd333.png)

**Comment by alexandredpy** [comment]
Dear @excoffit 
Issue has been resolved, thnaks to @DehnCrest 

Regards,
Alexandre
_Project Manager_
