### ISSUE TITLE
[FEATURE] Eggs exclamation

### ISSUE THREAD

**Issue by EUWOmelette** [DehnCrest/CantocheBot#15]
When the cantoche will have eggs on the menu, i want the bot to write "I LOVE EGGS!!!"

Can you do that ?

**Comment by alexandredpy** [comment]
Benjamin is currently working on this feature, on a secondary branch.

Regards,
Alexandre
_Project Manager_

**Comment by alexandredpy** [comment]
Branch has been merged.
Thanks for your work @EUWOmelette !

Regards,
Alexandre
_Project Manager_
