### ISSUE TITLE
[BUG] No more english version

### ISSUE THREAD

**Issue by alexandredpy** [DehnCrest/CantocheBot#18]
**Describe the bug**
Due to the migration to major Version 2, there is no more possibility to ask the bot in English.
We can only give in parameter a day in French.

**To Reproduce**
1. Type /cantoche day monday

**Expected behavior**
Like in major version 1, the bot should answer in English if we give him the day in English

**Environment:**
 - OS: Windows Server 2008 R2

**Comment by OlivierSTEPHAN** [comment]
Bonjour,
Où en est cette issue ? 
Aujourd'hui j'ai pu la reproduire via la commande /cantoche day tuesday
Je suis plutôt déçu et j'espère que cela va être réparé au plus vite.

**Comment by DehnCrest** [comment]
Hi all,

I'm pleased to announce that English version is back, along with some comments to help read the code

Best regards,
AKOE
