### ISSUE TITLE
[BUG] Issue with arguments

### ISSUE THREAD

**Issue by vlaujacky** [DehnCrest/CantocheBot#22]
---
name: Bug report
about: Bug on arguments : yesterday, today, tomorrow.
title: "[BUG]"
labels: bug

---

**Describe the bug**
The arguments 'yesterday', 'today' and 'tomorrow' are not understand by the bot.
Also, I do remember these commands worked with a different version of this.
**Unfortunately, there was a big deprecation of the bot on this new version...**

**To Reproduce**
1. Type the commands 
    
        !cantoche yesterday
        !cantoche today
        !cantoche tomorrow

2. See error 
            
        Votre jour n'a pas été compris, merci de réessayer

**Expected behavior**
I would appreciate to have a result with the menu of the argument that I gave.

**Environment:**
 - OS: All 

Regardless, 

An User.

**Comment by DehnCrest** [comment]
Hi,

The update has been pushed to the main repository, and should soon be deployed to the production.
Quick note though, after discussing with my manager, we would that the "yesterday" parameter wasn't needed, and the today command isn't too, as the !cantoche without any parameter already returns the current day's menu

Best regards,
AKOE
