### ISSUE TITLE
[FEATURE] Command Alias

### ISSUE THREAD

**Issue by vlaujacky** [DehnCrest/CantocheBot#28]
**Describe the solution you'd like**

On my smartphone, it's not practical to type :
                
        !cantoche 

Because there's no auto-completion on this command...
The best way would be to create an alias of !cantoche : 

        !ct 

**Additional context**

No additional context.

Regardless,

A User.

**Comment by alexandredpy** [comment]
Hello @vlaujacky ,
I'm gonna work on this feature, thanks your interest in this project.

Regards,
Alexandre
_Project Manager_

**Comment by alexandredpy** [comment]
Enhancement has been added [in this commit](https://github.com/DehnCrest/CantocheBot/commit/eb6d6757a418f1ec46e4d8ffff65ce0f476db3aa)

Thanks for your interest
Regards,
Alexandre
_Project Manager_
