### ISSUE TITLE
[FEATURE] Daily usage counter

### ISSUE THREAD

**Issue by alexandredpy** [DehnCrest/CantocheBot#30]
**Describe the solution you'd like**
I would appreciate to have a daily counter of the usage of the bot on Discord.
For example, we would call the bot with `!cantoche daily` , and it would return "Today, the bot has been used 45 times".

This counter would be reset at 0H00 each day.

**Additional context**
/

Thanks for you work,
Alexandre
_Project Manager_

**Comment by DehnCrest** [comment]
Hello,

That's a good idea, I'll work on it as soon as I can

BR,
AKOE

**Comment by alexandredpy** [comment]
AKOE,
Please have a look at these documents, it will be helpful for your work.

1. [Read a file with py](https://scipython.com/book/chapter-2-the-core-python-language-i/examples/reading-numbers-from-a-file/)
2. [Write in a file with py](https://scipython.com/book/chapter-2-the-core-python-language-i/examples/writing-numbers-to-a-file/)
3. [Generate a cron to reset file](https://stackoverflow.com/questions/35574603/run-cron-job-everyday-at-specific-time)

Regards,
Alexandre
_Project Manager_

**Comment by alexandredpy** [comment]
Feature has been added [in the 1.5 version ](https://github.com/DehnCrest/CantocheBot/pull/31)
