### ISSUE TITLE
[BUG] Multiple bugs

### ISSUE THREAD

**Issue by vlaujacky** [DehnCrest/CantocheBot#32]
---
name: Multiple bugs
about: Grammary and command return bugs.
title: "[BUG]"
labels: bug

---

**Describe the bug**

***First bug:*** 

When the bot "redownload" a new menu, there's a grammary error in the return of the command : 

    Menu "redownoaded", but it's still the previous week's menu

***Second bug:*** 
When the bot redownload a new menu, the command "!ct stats" doesn't return me the result expected

**To Reproduce**
***First bug:*** 
1. Go to the INFRES discord / SR Channel
2. Type :
   
        !ct
3. See error :

    Menu redownoaded, but it's still the previous week's menu

***Second bug:*** 
1. Go to the INFRES discord / SR Channel
2. Type :
   
        !ct stats
3. See error :

        Menu retéléchargé, mais il s'agit toujours du menu de la semaine dernière
        Menu redownoaded, but it's still the previous week's menu

**Expected behavior**
***First bug:*** 
Type :
   
        !ct
See result :

    Menu redownloaded, but it's still the previous week's menu

***Second bug:*** 
Type :
   
        !ct stats
See error :

        Le bot a été utilisé : x fois aujourd'hui
        The bot has been used x times today

**Environment:**

        Bot: CantocheBot - Version 1.5
        Python version: 3.10
        OS: Debian 10 Buster (amd64)

**Comment by alexandredpy** [comment]
Hello @vlaujacky

Thanks for your help in this project, the bug report is perfect!

@DehnCrest will work ASAP on these bugs, thanks again for your help.

Regards,
Alexandre
_Project Manager_
