### ISSUE TITLE
[BUG] Forcedownload argument is useless....

### ISSUE THREAD

**Issue by vlaujacky** [DehnCrest/CantocheBot#33]
---
name: An argument is useless...
about: The forcedownload argument is useless.
title: "[BUG]"
labels: bug

---

**Describe the bug**
The "forcedownload" argument is useless while the bot automatically redownloading the menu.

**To Reproduce**
1. Go to the INFRES discord / SR Channel
2. Type :
   
        !ct forcedownload
3. See error :

        Menu retéléchargé, mais il s'agit toujours du menu de la semaine dernière
        Menu redownoaded, but it's still the previous week's menu

**Expected behavior**

**Environment:**

        Bot: CantocheBot - Version 1.5
        Python version: 3.10
        OS: Debian 10 Buster (amd64)

**Comment by alexandredpy** [comment]
Hello @vlaujacky 
Thanks for you help, this feature will be removed ASAP by our developer @DehnCrest 

Regards,
Alexandre
_Project Manager_
