### ISSUE TITLE
[FEATURE] give tomorrow's menu after 1pm

### ISSUE THREAD

**Issue by vlaujacky** [DehnCrest/CantocheBot#35]
---
name: Next day menu after 13h
about: Send the next day menu after 13h.
title: "[FEATURE]"
labels: feature

---

**Describe the feature**
When past 13h, typing !ct or !cantoche send the next day menu.

**Environment:**

        Bot: CantocheBot - Version 1.5
        Python version: 3.10
        OS: Debian 10 Buster (amd64)

**Comment by alexandredpy** [comment]
Hello @vlaujacky 

We're currently working on it, thanks your interest in this project.

Regards,
Alexandre
_Project Manager_
