### ISSUE TITLE
[BUG] Crops are oversized

### ISSUE THREAD

**Issue by alexandredpy** [DehnCrest/CantocheBot#38]
**Describe the bug**
Due to the new format of menu, created by the school's restauration team, the crops of the designated day is out of scale.
The menu seems to describe now 3 different dishes : before it was 2 dishes.

**To Reproduce**
Call the bot
(See screenshots below)

**Expected behavior**
The today's menu should be well cropped. The developer has to define new scales.

**Screenshots**

![image](https://user-images.githubusercontent.com/18117508/148225723-d7a976a0-34b6-4b19-9aee-90207a821f18.png)
![image](https://user-images.githubusercontent.com/18117508/148225759-a844d4e1-fc4f-4ea7-a2a4-81a1025e5e0c.png)

**Comment by DehnCrest** [comment]
Hi,

I'm waiting until next week to be sure it's not exceptional, and if not, I'll implement a patch

Thanks for the report,
AKOE

**Comment by OlivierSTEPHAN** [comment]
Hi, 

I would like to have a feedback on this issue.
Is it still full bugged ?
Are you going to start working on it ?

OSTE

**Comment by alexandredpy** [comment]
> Hi,
> 
> I would like to have a feedback on this issue. Is it still full bugged ? Are you going to start working on it ?
> 
> OSTE

Hello @OlivierSTEPHAN 
IMHO, there is still something to fix, because the menu seems to be a little different now (new format)
Now, the developer must work on it ASAP, but I can't force him to work. @DehnCrest 

Regards,
Alexandre
_Project Manager_

**Comment by DehnCrest** [comment]
Hello,

This has been fixed in the new branch "bugfix_feb02". A pull request will follow to push it to the main branch
